spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://116.62.156.172:3306/capybaramall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000
logging:
  level:
    com.wvqnllb.capybaramall: debug